POST http://localhost:3003/signin
Content-Type: application/json

{
  "name": "Vanires",
  "email": "nena_festa@gmail.com",
  "password": "senha"
}


###
POST http://localhost:3003/login
Content-Type: application/json

{
  "email": "mesmo245@gmail.com",
  "password": "senha"
}


###
PUT http://localhost:3003/user/8c631ff4-856e-47f8-8617-3d375998a887
Content-Type: application/json

{
  "name": "Vanires",
  "email": "nena_festa@gmail.com"
}

###
GET http://localhost:3003/jobs

###
GET http://localhost:3003/job/5ffd42db-5d15c-9410-f3346e36a87a

###
GET http://localhost:3003/user/8c631ff4-856e-47f8-8617-3d375998a887

###
POST http://localhost:3003/jobs
Content-Type: application/json

{
  "title": "Web designer",
  "description": "desenvolvimento frontend",
  "phone": 71984707037,
  "period": "de seguna a sabado das 9:00 as 21:00"
}

###
POST http://localhost:3003/job/25c8f4aa-a6f5-4b38-b8ed-961e8f20849a
Content-Type: application/json

{
  "name": "Gazua",
  "phone": 71988500067,
  "user": 
}

###
POST http://localhost:3003/hired
Content-Type: application/json

{
    "email": "outr@gmail.com"
}


