GET http://localhost:3003/jobs

---
POST http://localhost:3003/jobs/signin
Content-Type: application/json

{
  "name": "Eu",
  "email": "eu@email.com",
  "password": "senha"
}

---
POST http://localhost:3003/jobs/login
Content-Type: application/json

{
  "email": "eu@email.com",
  "password": "senha"
}

---
POST http://localhost:3003/jobs
Content-Type: application/json

{
  "title": "Aulas de inglês",
  "description": "Aulas de inglês à domicílio",
  "price": 150,
  "dueDate": "10/02/2022",
  "payment": "débito e crédito"
}

---
POST http://localhost:3003/jobs/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiZDMyNzFkZWUtZTA1NC00ZTUwLWI5MzUtYzUzMmZiZTJlZmYzIiwiaWF0IjoxNjQwOTA3MjMwLCJleHAiOjE2NDA5OTM2MzB9.GQ9iMjZ1ZmKdy2EH9p9MTBxkxMl1WM3S3pAyCHOhqMU
Content-Type: application/json

{
  "title": "Diarista",
  "price": 300
}
